### PR TITLE
better error message when we don't find any services

### LINKED ISSUE #158: Better error message when `move2kube translate -s foo/` is run and no services are found.
When we do the one-step translation and it fails to find any services, it gives an unhelpful error message.
The current error message talks about being unable to fetch the answer.

Give a better error, something like: `Failed to find any services to translate.`

### PR DESCRIPTION
**Pull request by HarikrishnanBalagopal**
Signed-off-by: Harikrishnan Balagopal <harikrishmenon@gmail.com>

fix #158

### CODE REVIEW

File: internal/move2kube/planner.go [hunk 1]
```diff
@@ -69,6 +69,9 @@ func CuratePlan(p plantypes.Plan) plantypes.Plan {
 		cachepaths = append(cachepaths, p.Spec.Inputs.QACaches[i])
 	}
 	qaengine.AddCaches(cachepaths)
+	if len(p.Spec.Inputs.Services) == 0 {
```
Comment (ashokponkumar) [inline internal/move2kube/planner.go:72]: We have to do the same even if curate option is not selected. This code gets invoked only if we invoke the single command flow or translate -c.

**Review by ashokponkumar — CHANGES_REQUESTED** [review]

File: internal/move2kube/planner.go (hunk 1 above)
Comment (HarikrishnanBalagopal) [reply internal/move2kube/planner.go:72]: done

**Review by ashokponkumar — APPROVED** [review]
